defaults: &defaults
  docker:
      - image: circleci/node:8
  working_directory: ~/tmp/circlci-now

version: 2
jobs:
  unit-test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp/circlci-now
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run test # run tests
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp/circlci-now
      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now
      - deploy:
          name: Deploy & Alias
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                now --token $ZEIT_TOKEN --local-config .now/now.production.json
                now --token $ZEIT_TOKEN --local-config .now/now.production.json alias
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
                now --token $ZEIT_TOKEN --local-config .now/now.staging.json
                now --token $ZEIT_TOKEN --local-config .now/now.staging.json alias
            fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - unit-test
      - deploy:
          requires:
            - unit-test
          filters:
            branches:
              only:
                - master
                - develop
